name: Generate Documentation

permissions:
  contents: read

on:
  push:
    branches:
    - dev
  workflow_dispatch: # allows this workflow to be manually triggered

env:
  SPACEMAN_DMM_VERSION: suite-1.11

jobs:
  PreFlight:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: paths-filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: filter
        with:
          filters: .github/workflow-config/preflight-filters.yml
    outputs:
      dm: ${{ steps.filter.outputs.dm }}
  generate_documentation:
    permissions:
      contents: write # required to push the doc commit
    runs-on: ubuntu-22.04
    needs: PreFlight
    if: |
      (needs.PreFlight.outputs.dm == 'true') &&
      !contains(github.event.head_commit.message, '[ci skip]')
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup Cache
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7
        with:
          path: ~/spaceman_dmm/${{ env.SPACEMAN_DMM_VERSION }}
          key: ${{ runner.os }}-spacemandmm-${{ env.SPACEMAN_DMM_VERSION }}
      - name: Install dmdoc
        run:  scripts/install-spaceman-dmm.sh dmdoc
      - name: Generate documentation
        run: |
          ~/dmdoc
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dmdoc
          target-folder: docs
          clean: true
